version: '3.7'
services:
  blog_server_db:
    image: postgres:13-alpine
    container_name: blog_server_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-weak-password
    volumes:
      - c:/postgres/db:/var/lib/postgressql/data
    ports:
      - 5432:5432
  blog_server_pgadmin:
    image: dpage/pgadmin4
    container_name: blog_server_pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com 
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - 8080:80
    volumes:
      - c:/postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - blog_server_db
